AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Parameters:
  Stage:
    Type: String
    Default: staging
    Description: Parameter for getting the deployment stage

Resources:
  SimplePingApi:
     Type: AWS::Serverless::Api
     Properties:
       StageName: 
        Fn::Sub: '${Stage}'
       Auth:
         ApiKeyRequired: false
  SimplePingFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: src/index.handler
      Runtime: nodejs14.x
      FunctionName:
        Fn::Sub: '${Stage}SimplePing'
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::765065967862:role/service-role/PreProdTS-role-6kmsulog'
      Events:
        PublicApi:
          Type: Api
          StageName: 
            Fn::Sub: '${Stage}'
          Properties:
            Path: /ping
            Method: ANY
            RestApiId:
               Ref: SimplePingApi
Outputs:
  SimplePingApi:
    Description: "API Gateway endpoint URL for Prod stage for SimplePing function"
    Value: !Sub "https://${SimplePingApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/SimplePing/"
  SimplePingFunction:
    Description: "SimplePing Lambda Function ARN"
    Value: !GetAtt SimplePingFunction.Arn
